### ISSUE TITLE
Support for pseudo classes

### ISSUE THREAD

**Issue by Leinnan** [afonsolage/bevy_ecss#18]
Is there any chance for supporting pseudo classes like `:hover` and `:focus` for `Interaction` elements?

**Comment by Leinnan** [comment]
I did create some code to detect and parse psuedo classes, but I am not quite sure how to approach filtering and so on. There is a patch:
https://gist.github.com/Leinnan/9c46bc762fc80773baedb43273fb4e8b

**Comment by Leinnan** [comment]
I was able to create a repo with a branch that would implement pseudo classes, but for now it is unoptimized- it needs to update all of the nodes after each hover/focus event:
https://github.com/Leinnan/bevy_ecss/tree/my_take

**Comment by TheBeardedQuack** [comment]
Also my take on implementing pseudo-classes (with CSS ordering fix in place).

https://bitbucket.org/TheBeardedQuack/tomt-bevycss/src/45dd618f9d41aa5d66f40a839f61d5186a51edad/
