### ISSUE TITLE
Bevy 0.12 Support

### ISSUE THREAD

**Issue by Leinnan** [afonsolage/bevy_ecss#24]
You can just grab my last 3 commits from here: https://github.com/Leinnan/bevy_ecss/commits/0.12
Should be good enough

**Comment by afonsolage** [comment]
For some reason, I wasn't receiving any updates from issues or PRs on my own repo. Sorry, I'll update `bevy_ecss` to 0.12. I've updated already to 0.11. I'll do the next one until tomorrow.
