### ISSUE TITLE
Update `cssparser` dependency

### ISSUE THREAD

**Issue by Leinnan** [afonsolage/bevy_ecss#31]
This bevy plugin heavily relies on `cssparser` dependency. It would be nice to have this updated. It is a non-trivial task because since last update the crate changed.

**Comment by afonsolage** [comment]
I've created a PR, if you would like to check: https://github.com/afonsolage/bevy_ecss/pull/32.

I'll marge it by tomorrow and I'm planing releasing version `0.5.1`, which includes the #27, #28 and #32.

**Comment by Leinnan** [comment]
Nice one! One thing worth considering could be adding `CHANGELOG.md` file to this repo maybe?
